### ISSUE TITLE
Suggestion: Avoid using git protocol in [sources]

### ISSUE THREAD

**Issue by idgserpro** [collective/training_buildout#1]
Some corporate environments block the git protocol. Although I can use the [insteadOf option](https://git-scm.herokuapp.com/docs/git-clone) I think it would be better to just use the https protocol for [starzel.votable_behavior](https://github.com/collective/training_buildout/blob/master/buildout.cfg#L82).

**Comment by pbauer** [comment]
thanks. will do.

**Comment by idgserpro** [comment]
Any news?

**Comment by mpeeters** [comment]
Done bbe54942448c3679b95a73e21e3324189b481b8f
