### ISSUE TITLE
Plone5 rc3 housekeeping

### ISSUE THREAD

**Issue by fulv** [collective/training_buildout#7]
@pbauer: I've updated the buildout to rc3.  (Sorry I committed to the plone5 branch directly.)

A few notes:
  - [x] do we want to make plone5 the new master and default branch, like in plone.training?
  - [x] I assume we don't want to use coredev anymore, so I changed the buildout to be more similar to the unified installer.
  - [x] Consequently, can we get rid of buildout_not_coredev.cfg?

I get this warning when I run bootstrap:

```warning: manifest_maker: MANIFEST.in, line 9: unknown action 'recursive-ignore```

**Comment by fulv** [comment]
Also, in the Vagrant plone puppet file, do we still want to have two buildouts, one in `/home/vagrant`, and one in `/vagrant/buildout`?

**Comment by pbauer** [comment]
I did the three changes mentioned above.
 
The buildout in ``/home/vagrant/Plone`` is not used in the training and is only the result of running the unified installer. Since we actually only need the buildout-cache from the installer we could change it like this: https://github.com/plone/training/pull/133

**Comment by fulv** [comment]
Thanks!
Yes, I was aware of the fact that `/home/vagrant/Plone` was the target of the unified installer buildout, which was only used to get the eggs.  I was just wondering whether it would make sense to get rid of the coredev buildout (in `/vagrant/buildout`), and do the modifications we want to the unified installer cfg files.  But I like your solution better.
