### ISSUE TITLE
Plone 4 buildout.cfg eggs

### ISSUE THREAD

**Issue by catalinmititiuc** [collective/training_buildout#9]
On chapter 9, paragraph "Making the add-on packages available to Zope", the Products.PloneFormGen egg needs a version, for me Products.PloneFormGen==1.7.19 works.

**Comment by pbauer** [comment]
That shoudl be fixed now. The buildout and vagrant in the plone4-flavor now use Plone 4.3.10, bobtemplates.plone and updated versions of the addons
